name: 'Changelog Generator'
description: 'Automatically generate a CHANGELOG based on the releases in GitHub'

author: Vincent Boon <vincent@justbetter.nl>

inputs:
  repository:
    required: true
    description: The GitHub repository. owner/repo

branding:
  icon: copy
  color: purple

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
