name: 'Changelog Generator'
description: 'Automatically generate a CHANGELOG based on the releases in GitHub'

author: Vincent Boon <vincent@justbetter.nl>

inputs:
  repository:
    required: true
    description: The GitHub repository. owner/repo

  sha:
    required: false
    description: Filter on branch / commit

branding:
  icon: copy
  color: purple

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.sha }}
    - /github/workspace/CHANGELOG.md
